import org.springframework.samples.petclinic.ratelimiter.RuleRequest;
global org.springframework.samples.petclinic.ratelimiter.RuleResponse ruleResponse;

dialect "mvel"

rule "Ip address based rate limit"
    when
        RuleRequest(count>=2 && ipAddress != "127.0.0.1")
    then
        System.out.println("==========denying request=============");
        ruleResponse.setResponse(true)
end
rule "Unique IP Address"
    when
       RuleRequest(count>=10 && ipAddress=="127.0.0.1")
      then
        System.out.println("==========denying request=============");
        ruleResponse.setResponse(true)
end
